# Generated by Django 4.2.3 on 2023-08-10 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="video",
            field=models.FileField(null=True, upload_to="videos"),
        ),
    ]
